# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 16:56
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=155)),
                ('district', models.CharField(max_length=155)),
                ('state', models.CharField(max_length=155)),
                ('address', models.CharField(max_length=155)),
                ('picture', models.ImageField(upload_to='media', verbose_name='image')),
                ('about', models.CharField(max_length=255)),
                ('licence', models.ImageField(upload_to='media', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=155)),
                ('district', models.CharField(max_length=155)),
                ('state', models.CharField(max_length=155)),
                ('address', models.CharField(max_length=155)),
                ('picture', models.ImageField(upload_to='media', verbose_name='image')),
                ('about', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('skill', models.CharField(max_length=155)),
                ('rate_per_day', models.IntegerField()),
                ('status', models.CharField(choices=[('H', 'Hire'), ('N', 'Not hire')], default='N', max_length=1)),
                ('hired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_contr_hire', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
