# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_contractor_profile', related_query_name=(), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_worker_profile', related_query_name=(), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workerskill',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_user_skill', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='workerskill',
            unique_together=set([('user', 'skill')]),
        ),
    ]
