# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 19:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_auto_20180412_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerskill',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 13, 0, 56, 55, 718000)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workerskill',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 13, 0, 56, 59, 19000)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_contractor_profile', related_query_name='<QuerySet [<User: 8888888889>]>', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_worker_profile', related_query_name='<QuerySet [<User: 9999999999>, <User: 9797979797>, <User: 8888888888>]>', to=settings.AUTH_USER_MODEL),
        ),
    ]
