# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-15 09:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_auto_20180415_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcheck',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workerskill',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='workerskill',
            name='hired_by',
        ),
        migrations.RemoveField(
            model_name='workerskill',
            name='to_date',
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_contractor_profile', related_query_name='<QuerySet [<User: 8888888889>, <User: 9889797955>, <User: 9889797956>]>', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_worker_profile', related_query_name='<QuerySet [<User: 9999999999>, <User: 9797979797>, <User: 8888888888>, <User: 9989787878>, <User: 4656456465>, <User: 4549975652>, <User: 9889898989>, <User: 9099600792>, <User: 8949989598>]>', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='OtpCheck',
        ),
    ]
