# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-15 18:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worker', '0005_auto_20180415_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('status', models.CharField(choices=[('request', 'request'), ('confirm', 'confirm'), ('finish', 'finish')], default='request', max_length=15)),
                ('hired_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hired_by', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_worker_skill', to='worker.WorkerSkill')),
            ],
        ),
    ]
